name: "Release"

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: |
        echo $RELEASE_VERSION
        mkdir -p dist
        export name=csv2sql-darwin-amd64-$RELEASE_VERSION
        GOOS=darwin GOARCH=amd64 GO111MODULE=on go build -ldflags='-X "main.Version=$(RELEASE_VERSION)"' -o dist/$name
        export name=csv2sql-darwin-arm64-$RELEASE_VERSION
        GOOS=darwin GOARCH=arm64 GO111MODULE=on go build -ldflags='-X "main.Version=$(RELEASE_VERSION)"' -o dist/$name
        export name=csv2sql-linux-amd64-$RELEASE_VERSION
        GOOS=linux GOARCH=amd64 GO111MODULE=on go build -ldflags='-X "main.Version=$(RELEASE_VERSION)"' -o dist/$name
        export name=csv2sql-linux-arm64-$RELEASE_VERSION
        GOOS=linux GOARCH=arm64 GO111MODULE=on go build -ldflags='-X "main.Version=$(RELEASE_VERSION)"' -o dist/$name
        export name=csv2sql-windows-32bit-$RELEASE_VERSION.exe
        GOOS=windows GOARCH=386 GO111MODULE=on go build -ldflags='-X "main.Version=$(RELEASE_VERSION)"' -o dist/$name
        export name=csv2sql-windows-amd64-$RELEASE_VERSION.exe
        GOOS=windows GOARCH=amd64 GO111MODULE=on go build -ldflags='-X "main.Version=$(RELEASE_VERSION)"' -o dist/$name

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          files: dist/*.*